language: python
python:
  - "2.7"
  - "3.6"
# https://snarky.ca/how-to-use-your-project-travis-to-help-test-python-itself/
  - "3.6-dev"
  - "3.7-dev"
env:
  matrix:
    - VERSION_FOR_PIP=8.1.2
    - VERSION_FOR_PIP=9.0.3
install:
  - pip install -r dev-requirements.txt
  - pip install pip==$VERSION_FOR_PIP
script: pre-commit run --all-files
